### ISSUE TITLE
need help about zsh: parse error near `\n'

### ISSUE THREAD

**Issue by Andyf0** [andrey-yantsen/tlscontact-appointment-finder#6]
Hi Andrey! When i copy the following command to the terminal and it not work and feedback "zsh: parse error near `\n'". Which step i got wrong?

**Comment by andrey-yantsen** [comment]
Are you sure you have replaced all the things like `<APPLICATION_REFERENCE>` with the appropriate values?

**Comment by Andyf0** [comment]
> Are you sure you have replaced all the things like `<APPLICATION_REFERENCE>` with the appropriate values?

Yeap! After git clone the code, I pip3 a docker-compose and the version is 1.29.2. 
I am not sure is the --search-before <November 15>  value get wrong?
and the follower is my command:

docker-compose run tlscontact \
  --tls-application-reference <M1114xxxx> \
  --login <mlxxx@lxxxxs.ac.uk> \
  --password <Aa123456!> \
  --search-before <November 15> \
  --telegram-bot-token <5619939024:AAFH_IcRyq7AL1_zsxxxxxxxx> \
  --telegram-chat-id <5361408620>

**Comment by andrey-yantsen** [comment]
@Andyf0, you must replace the whole thing, including the triangle braces — as you did with the email. As for the date, you need to provide it in the format of `YYYY-MM-DD`, e.g. `2022-11-15`.

**Comment by Andyf0** [comment]
@andrey-yantsen, I got a lot of error, so is my environment problems?
sorry to bother U!

Traceback (most recent call last):
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fengweihua/opt/anaconda3/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/Users/fengweihua/opt/anaconda3/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

**Comment by Andyf0** [comment]
Thanks!! it run! but my telegram send a two message for me:

Got an exception! HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8d56cbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Got an exception! Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.jsm:12:1
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:192:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:404:5
element.find/</<@chrome://remote/content/marionette/element.js:291:16

Also i can see in my docker desktop got 3 containers all is in running but i can't stop or pause it.

**Comment by andrey-yantsen** [comment]
I think it's just because selenium is slow to boot :) The script should retry automatically in 1.5 hours. Or you need to find a way to restart the `tlscontact` container without restarting the other one with selenium.

**Comment by andrey-yantsen** [comment]
P.S. There's a chance that the whole thing is just broken. It's been almost six months since I checked it last time.
