### ISSUE TITLE
Landing page prevents the script from looking up

### ISSUE THREAD

**Issue by yitingfeng** [andrey-yantsen/tlscontact-appointment-finder#9]
https://visa-fr.tlscontact.com/gb/LON/login.php has added a landing page, asking user to verify that they are human, which stops the script from discovering the elements.

**Comment by EugeneYushin** [comment]
@yitingfeng Do you have an error message?

That's what I see on startup:
```
[2023-02-19 22:51:52] [ERROR] Got error
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 68, in <module>
    WebDriverWait(driver, 10).until(EC.visibility_of_element_located((By.ID, 'email')))
  File "/usr/src/app/.venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:392:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16
```

**Comment by Nikitich2033** [comment]
@EugeneYushin I have the exact same error. They added a GeeTest slider captcha before the login page.

**Comment by yuhan1010** [comment]
@EugeneYushin Me 2, same problem.

**Comment by Z-Guo** [comment]
anyone found a solution to this?
